
server:
  port: 8081

#Configurações do Banco de Dados
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/app?createDatabaseIfNotExist=true&serverTimeZone=UTC
    username: root
    password: root


algafood:
  jwt:
    keystore:
      path: keystores/algafood.jks
      password: 123456
      keypair-alias: algafood


#logging:
#  level:
#   org:
#      springframework: DEBUG



